USE AbsensiDB;
GO

-- Drop the existing constraint (Name might vary, so we use a dynamic approach or just try to alter if possible)
-- Since we can't easily know the random name generated by SQL Server, we will try to drop it by checking sys.check_constraints
DECLARE @ConstraintName nvarchar(200)
SELECT @ConstraintName = Name FROM sys.check_constraints WHERE parent_object_id = OBJECT_ID('tblUser') AND definition LIKE '%Role%'

IF @ConstraintName IS NOT NULL
BEGIN
    EXEC('ALTER TABLE tblUser DROP CONSTRAINT ' + @ConstraintName)
END
GO

-- Add the new constraint
ALTER TABLE tblUser ADD CONSTRAINT CK_User_Role CHECK (Role IN ('Admin', 'HR', 'Atasan', 'Karyawan'));
GO
